export const GET_USER = "GET_USER";

export const GET_ARTICLES = "GET_ARTICLES";

export const GET_TRANSACTIONS = "GET_TRANSACTIONS";

export const GET_BENEFICIARIES = "GET_BENEFICIARIES";

export const GET_CATEGORIES = "GET_CATEGORIES";